/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GuiView;

import LibraryModel.Admin;
import LibraryModel.Book;
import LibraryModel.Client;
import LibraryModel.Item;
import LibraryModel.Message;
import LibraryModel.User;
import static Main.Main.validateID;
import static Main.Main.validatePassword;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author tseow
 */
public class LoginWindow extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    private ArrayList<Admin> Admins;
    private ArrayList<Client> Clients;
    private ArrayList<Item> Items;
    private ArrayList<Message> Messages;
    private ClientWindow clientView;
    private AdminWindow adminView;
    
    public LoginWindow(ArrayList<Admin> admins, ArrayList<Client> users, ArrayList<Item> items, ArrayList<Message> messages) {
        initComponents();
        
        Clients = users;
        Items = items;
        Admins = admins;
        Messages = messages;
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        idTextBox = new javax.swing.JTextField();
        PasswordTextbox = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        label1.setText("Enter ID:");

        label2.setText("Enter Password");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(PasswordTextbox, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                        .addComponent(idTextBox)
                        .addComponent(loginButton)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(PasswordTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loginButton)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        label3.setText("Tim's Library");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
      validateLogin();
      
    }//GEN-LAST:event_loginButtonActionPerformed

    public void validateLogin()
    {
        
         for(Admin a : Admins)
        {
            if (a.getId().equals(idTextBox.getText()))
            {
                if (a.getPassword().equals(getUserPasswordInput())) 
                {              
                    //JOptionPane.showMessageDialog(this, "Correct");
                    this.setVisible(false);
                    idTextBox.setText("");
                    PasswordTextbox.setText("");
                    adminView = new AdminWindow(a, Clients, Items, Messages, this);
                    adminView.setVisible(true);
                    return;
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Password is incorrect");
                }         
            }
            
        }
        
        for(Client c : Clients)
        {
            if (c.getId().equals(idTextBox.getText()))
            {
                if (c.getPassword().equals(getUserPasswordInput())) 
                {              
                    //JOptionPane.showMessageDialog(this, "Correct");
                    this.setVisible(false);
                    idTextBox.setText("");
                    PasswordTextbox.setText("");
                    clientView = new ClientWindow(c, Items,Messages, this);
                    clientView.setVisible(true);
                    return;
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Password is incorrect");
                }         
            }
            
        }
        
        JOptionPane.showMessageDialog(this, "User does not exist");
    }
    
    public String getUserPasswordInput()
    {
        String passwordString = "";
        
        char[] pass = PasswordTextbox.getPassword();
        
        for (int i = 0; i < pass.length; i++) {
            
            passwordString += pass[i];
        }
        
        return passwordString;
    }
    
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PasswordTextbox;
    private javax.swing.JTextField idTextBox;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private javax.swing.JButton loginButton;
    // End of variables declaration//GEN-END:variables
}
